name: balls-app
region: lon

services:
  - name: predicting-ball
    github:
      repo: Paulj1989/predicting-ball
      branch: main
      deploy_on_push: true

    dockerfile_path: /Dockerfile
    source_dir: /
    http_port: 8501

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

    routes:
      - path: /

    health_check:
      http_path: /_stcore/health
      port: 8501
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
        scope: RUN_TIME
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
        scope: RUN_TIME
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
        scope: RUN_TIME

domains:
  - domain: predicting-ball.co.uk
    type: PRIMARY
    zone: predicting-ball.co.uk

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
